---

  - name: Create folder for Docker server certificates
    file:
      path: "{{cert_dest_path}}"
      state: directory
      mode: 0750
      seuser: system_u
    become: yes

  - name: Generate certs (on control machine); requires Galaxy role "easypath.generate-tls-certs"
    import_role: 
      name: easypath.generate-tls-certs

  - name: Copy certificates for Docker server
    copy: 
      src: "{{item.src}}"
      dest: "{{item.dest}}"
      mode: 0640
    become: yes
    with_items:
      - { src: "{{cert_src_path}}/{{tls_ca_cert}}", dest: "{{cert_dest_path}}/{{tls_ca_cert}}" }
      - { src: "{{cert_src_path}}/{{inventory_hostname_short}}.pem", dest: "{{cert_dest_path}}/{{inventory_hostname_short}}.pem" }
      - { src: "{{cert_src_path}}/{{inventory_hostname_short}}.key", dest: "{{cert_dest_path}}/{{inventory_hostname_short}}.key" }
    when:
      - cert_src_path is defined
      - tls_ca_cert is defined

  - name: Create folder for client certificates
    file:
      path: "{{ ansible_env.HOME }}/.docker"
      state: directory
      mode: 0750
    become_user: "{{profile_user}}"
    when:
      - config_profile_docker_client_tls

  - name: Copy client certificates to profile; enables Docker client to connect using TLS by default
    copy: 
      src: "{{item.src}}"
      dest: "{{item.dest}}"
      mode: 0640
    with_items:
      - { src: "{{cert_src_path}}/{{tls_ca_cert}}", dest: "{{ ansible_env.HOME }}/.docker/ca.pem" }
      - { src: "{{cert_src_path}}/{{tls_client_cert}}", dest: "{{ ansible_env.HOME }}/.docker/cert.pem" }
      - { src: "{{cert_src_path}}/{{tls_client_key}}", dest: "{{ ansible_env.HOME }}/.docker/key.pem" }
    become_user: "{{profile_user}}"
    when:
      - config_profile_docker_client_tls
      - cert_src_path is defined
      - tls_ca_cert is defined
      - tls_client_cert is defined
      - tls_client_key is defined

  - name: Update Docker environment variables in profile
    lineinfile:
      path: "{{ ansible_env.HOME }}/.bashrc"
      line: export DOCKER_HOST=tcp://{{docker_engine_bind_ip}}:2376 DOCKER_TLS_VERIFY=1
    become_user: "{{profile_user}}"
    when:
      - config_profile_docker_client_tls
